### ISSUE TITLE
Resolve the ephemeral issue

### ISSUE THREAD

**Issue by Zuytan** [UTT-Alumni/Discord-Bot#2]
Currently, the message sent is not ephemeral so everybody can see it.
We must find a solution about it.

Possible solution:
- Delete the message after the user validate it
- Ask the user to type a specific command once he first connect
- Send a PM to the new user

**Comment by burgerni10** [comment]
I think my implementation fix this issue.

What it does now: 
1. The bot retrieve the channel messages
2. If no message, a "welcome message" is published by the bot, with a button ton create the interaction
3. The user click on the button to accept the rules and receives the new role

<img width="926" alt="image" src="https://user-images.githubusercontent.com/28055217/198719398-a52cc540-8cd3-45ef-a3db-658813a0d12c.png">
